### ISSUE TITLE
Simplificar 01-basefn

### ISSUE THREAD

**Issue by marcelovmaciel** [marcelovmaciel/Pudley#4]
Ver se da para fazer isso. Talvez seja melhor resolver outras questoes antes

**Comment by acrmartins** [comment]
Montes de comentários breves aqui no email. Parece que você está
trabalhando nisso e informando tudo! :p

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by marcelovmaciel** [comment]
Eitaaa hahahaha provavelmente pq o senhor esta watching o repo!

**Comment by acrmartins** [comment]
Parece que sim. Cuidado com os comentários, tem gente assistindo!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
