### ISSUE TITLE
Separar funcoes de plots

### ISSUE THREAD

**Issue by marcelovmaciel** [marcelovmaciel/Pudley#5]
- Ta um inferno o test-design
- Os comandos de plottagem podem ser abstraidos e virar fns

**Comment by marcelovmaciel** [comment]
N consegui lidar com tanto codigo sujo e movi as funcoes de plot para outro arquivo. Fica faltando:
- terminar de retirar elas de 01
- fazer o docstring de algumas delas 
- e ai partir para outros issues

**Comment by acrmartins** [comment]
Para você saber sobre o que se trata esse novo trabalho:

https://www.quantamagazine.org/why-is-the-universe-expanding-so-fast-20200427/?fbclid=IwAR1d6CBley1czRegFKSZ13YSxMIY1wMpGK8NDKBwhplk2xpleJiAJP_N6j4

**Comment by marcelovmaciel** [comment]
Professor, lerei sem falta!

- Issue resolvida em  https://github.com/marcelovmaciel/Pudley/commit/874a65c5202db5e4c56ad1d9555d45558aa22aff

**Comment by acrmartins** [comment]
Eu cuido dessa parte do texto, claro, mas é bom saber qual o problema que
eu tenho em mente como o tópico com que podemos contribuir.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by acrmartins** [comment]
Ah, sim, parece que você foi citado aqui:

https://arxiv.org/abs/2004.14548

:p

**Comment by acrmartins** [comment]
Cinco vagas:

https://www.unitn.it/drss/srs/19?fbclid=IwAR2OIjtMi2DCC_uqZMxEhIaTPcEd_O7z8OkAUYtxQnh4_wvcRQ6s6PtTlp8

**Comment by marcelovmaciel** [comment]
Professor so vi agora. Nao recebo por email a movimentacao aqui e como fechei a issue acabei vendo agora por acaso! Sacarei essas vagas em trento, minha namorada por sinal foi aceita no mestrado desse departamento :))
