### ISSUE TITLE
Add DrWatson como dependency 

### ISSUE THREAD

**Issue by marcelovmaciel** [marcelovmaciel/Pudley#8]
A análise em Poodl foi o que deu mais trabalho. O codigo virou um caos.

Hoje passei o dia modularizando parte da analise. O correto, contudo, é usar  o pacote específico para isso, DrWatson.

Implementar a analise que esta no testdesign usando DrWatson resolve essa issue.

**Comment by marcelovmaciel** [comment]
Olhei aqui e nao é tao trivial migrar para drwatson. Vou implementar outras issues antes.

**Comment by acrmartins** [comment]
Elementary, Dr Watson

**Comment by marcelovmaciel** [comment]
kkkkkkkkkkkkkkkkkkkkk
